### ISSUE TITLE
Error: no 3-points pharmacophore models above thresholds.

### ISSUE THREAD

**Issue by syedzayyan** [meddwl/psearch#14]
I get this error when trying to train on a small dataset of 128 ligands.

I would have believed this error but it previously worked and generated models, but it's not working anymore.

**Comment by DrrDom** [comment]
As far as I remember we did not observe instability in repeated modeling. The only point, which I remember and where randomness may be introduced, is clustering. If `Butina.ClusterData` is not fully deterministic then the order of points in individual clusters may change. This will affect training set formation, because we take first 5 points for a training set from each cluster. I think that output of `Butina.ClusterData` may depend on the input order of molecules. So if you rearrange your starting SMILES this may also change the output. Try to check every step you did previously and input files.
If now you run the program with identical inputs and get the same outputs (this error message) this would support reproducibility of the implemented workflow.

**Comment by syedzayyan** [comment]
Thank you for the comment. I am using an external database, so it could be that they got sorted differently.
