### ISSUE TITLE
scoring for VS hits

### ISSUE THREAD

**Issue by suneelbvs** [meddwl/psearch#8]
Hi,

Does screendb generates any scoring/fit value/RMSD for VS hits?. Also, does it gives any information about no of features to each VS Hit?

Looking forward for your reply.

Regards,
Suneel

**Comment by DrrDom** [comment]
Hi Suneel,
1. We do not return scoring because matching between pharmacophores is determined based on the non-alignment approach. Therefore the scoring is binary - fit or not-fit.
2. Currently the script screen_db checks for matching of all features in a model to a given molecule. So, if your model has 5 features and a molecule matched this model, it means that all 5 features were found.

**Comment by suneelbvs** [comment]
Thank you @DrrDom for your response.
